project:
  type: website

website:
  title: "Mastering Data Visualization with ggplot2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Sessions
        menu:
        - href: sessions/1_introduction.qmd
          text: 1. Introduction
        - href: sessions/2_ggplot2.qmd
          text: 2. Modern ggplot2
        - href: sessions/3_text_fonts.qmd
          text: 3. Text rendering and font use
        - href: sessions/4_theme_guide.qmd
          text: 4. Styling your plot
        - href: sessions/5_composition.qmd
          text: 5. Plot composition
        - href: sessions/6_interaction.qmd
          text: 6. Interactive plots
        - href: sessions/7_extensions.qmd
          text: 7. Creating extensions
        - href: sessions/8_fun.qmd
          text: 8. Spice up your plot

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true


filters:
  - plain-div.lua

