project:
  type: website

website:
  title: "Mastering Data Visualization with ggplot2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Sessions
        menu:
        - text: Session 1
        - href: sessions/1_introduction.qmd
          text: Introduction
        - href: sessions/2_ggplot2.qmd
          text: Modern ggplot2
        - text: Session 2
        - href: sessions/3_text_fonts.qmd
          text: Text rendering and font use
        - href: sessions/4_theme_guide.qmd
          text: Styling your plot
        - text: Session 3
        - href: sessions/5_composition.qmd
          text: Plot composition
        - href: sessions/6_interaction.qmd
          text: Interactive plots
        - text: Session 4
        - href: sessions/7_extensions.qmd
          text: Creating extensions
        - href: sessions/8_fun.qmd
          text: Spice up your plot

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true


filters:
  - plain-div.lua

