on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.0'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            tidyverse/ggplot2
            any::patchwork
            r-lib/marquee
            any::systemfonts
            davidgohel/ggiraph#322
            any::legendry
            any::ggfx
            any::ggpattern
            any::gridpattern
            any::tibble
            any::dplyr
            any::palmerpenguins
            any::gapminder
            any::gganimate
            any::plotly
            any::gifski
            any::gridGraphics

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
